### ISSUE TITLE
Select 5 Simple MSS that already have TEI XML files

### ISSUE THREAD

**Issue by davidamichelson** [srophe/wright-catalogue#20]
Try to find ones that would be easy for a script.

**Comment by davidamichelson** [comment]
Please link to them here.

**Comment by wlpotter** [comment]
@davidamichelson see the following examples:

1. [Add. 14,491. Vol 1, p. 181-182](https://github.com/srophe/srophe-app-data/blob/dev/data/manuscripts/tei/571.xml)
2. [Add. 17,173. Vol. 2, p. 726-729](https://github.com/srophe/srophe-app-data/blob/dev/data/manuscripts/tei/825.xml)
(With the exception of the sub-items of [msItem a3](https://github.com/srophe/srophe-app-data/blob/dev/data/manuscripts/tei/825.xml#L177) and [a6](https://github.com/srophe/srophe-app-data/blob/dev/data/manuscripts/tei/825.xml#L302), which were not clearly outlined by Wright but were delineated by the encoder.)
3. [Add. 17,192. Vol. 2, p. 778-781](https://github.com/srophe/srophe-app-data/blob/dev/data/manuscripts/tei/848.xml)
4. [Add. 17204. Vol. 3, p. 1081](https://github.com/srophe/srophe-app-data/blob/dev/data/manuscripts/tei/866.xml)
5. [Add. 14607. Vol. 2, p. 683-684](https://github.com/srophe/srophe-app-data/blob/dev/data/manuscripts/tei/343.xml)
