### ISSUE TITLE
MS Parts to Follow Up on

### ISSUE THREAD

**Issue by davidamichelson** [srophe/wright-catalogue#22]
- [ ] https://app.asana.com/0/1133542327299194/1170058424202045 

- [ ] https://app.asana.com/0/1139445457802343/1174506216280749 

- [ ] https://github.com/srophe/wright-catalogue/tree/master/data/4_to_be_checked/need-ms-parts

**Comment by wlpotter** [comment]
I'm not sure what the two asana links are for? But the `/data/4_to_be_checked/need-ms-parts/` directory has been fully encoded and edited. I'm going to close this issue.

**Comment by davidamichelson** [comment]
Me neither, thanks!
