### ISSUE TITLE
Make sure files from https://github.com/srophe/wright-catalogue/pull/23 were processed

### ISSUE THREAD

**Issue by wlpotter** [srophe/wright-catalogue#29]
These files were merged in, but I'm not sure they've undergone post-processing and editing.

I can take a look at them, unless you remember @davidamichelson ?

**Comment by davidamichelson** [comment]
Thanks! No processing has been done at all yet.

**Comment by wlpotter** [comment]
Sounds good, I will make sure to run them through the scripts and pull out any that need msParts

**Comment by davidamichelson** [comment]
Thanks, fyi alot of them are MS Parts

**Comment by wlpotter** [comment]
These have been processed and are in the pipeline; I have split off the ones that are msParts for separate handling.
