### ISSUE TITLE
Provisional data model for Catenae

### ISSUE THREAD

**Issue by wlpotter** [srophe/wright-catalogue#58]
Editorial note for this provisional data model (for future reference, etc.): I have included Wright's description of Catenae (usually arranged by the 'most cited' author, then other authorities in alphabetical order) in a tei:note. For the longer descriptions, I've followed Wright's paragraph divisions using tei:p elements within the tei:note. I have tried to tag folia with tei:locus elements and entities with tei:persName, tei:placeName. For works that are cited, I have used a tei:title. I have not, however, tagged rubrics, incipits, etc. choosing instead to leave all of these as tei:quote elements with xml:lang="syr" attributes.

**Comment by wlpotter** [comment]
I have only tagged the titles themselves with tei:title. If Wright gives multiple chapters and folia ranges as in the following example from 894 (2:915-917; Add. 17,214), I tag the locus but not the chapter as these are assumed to be attached to the already cited title.

```
<p>
<title>Homiliae Epithron.</title>: xvi., <locus>fol. 71 b</locus>; xxv., <locus>fol. 34 a</locus>;...[etc.]
</p>
```

**Comment by wlpotter** [comment]
Add a `<change @type="planned" @subtype="consultation">` element to the tei:revisionDesc. This will let us know we need to go back to get the ms to see what the folia order is for citations

**Comment by wlpotter** [comment]
Here is a more detailed and organized account, with examples taken from ms-262 (Add. 14,535, vol. 2:796-799):

1. Tag the manuscript with `<change @type="planned" @subtype="consultation">` using the button on the author-mode form
2. Use a tei:note element within the tei:msItem of the catena work to capture information about the cited authors, e.g.:
```
<msItem>
  <title xml:lang="en">A treatise against the Nestorians, compiled by a Monophysite</title>
  <note>The first five chapters are either lost or imperfect.</note>
  <note><!-- CATENA INFO GOES HERE --></note>
  <msItem>...<!--note that in this ms the chapters that exist should be included as sub-items --></msItem>
<msItem>
```

3. Within the tei:note element containing the catena information, follow Wright's paragraph divisions by using a child tei:p element within the tei:note. You should refer to the PDF to verify the paragraph-breaks.

```
<note>
  <p>The authorities cited are--</p>
  <p>Addai, or Thaddseus: ...</p>
  <p>Alexander of Alexandria...</p>
  ...
</note>
```

4. Within the tei:p elements, tag the following entities:
    - authors (and other persons) with tei:persName
    - English or Latin titles of works with tei:title, and given the corresponding `@xml:lang` attribute ("en" for English, "la" for Latin)
    - Strings of Syriac characters should be tagged with a tei:quote element and `@xml:lang="syr"`.
        - The same goes for Greek, which should be tagged with `<quote xml:lang="grc">`
    - folio numbers should be tagged with tei:locus
    - references to secondary scholarly literature should be tagged with a tei:bibl
    - references to other manuscripts should also be tagged with a tei:bibl

Here is an example of these:
```
<p><persName>Addai</persName>, or <persName>Thaddaeus</persName>: <quote xml:lang="syr">ܡܢ ܡܠܦܢܘܬܐ ܕܥܒ̣ܕ ܒܐܘܪܗܝ ܩܕܡ ܐܒܓܪ ܡܠܟܐ ܘܟܢܫܐ ܕܡܕܝܢܬܐ</quote>. <locus>Fol. 1 a</locus>. See <bibl>Cureton's Ancient Syr. Doc., pp. $ ܩܚ, 108, and 192</bibl>.</p>
<p><persName>Cyril of <placeName>Alexandria</placeName>: <title>comment, on 1 Corinthians</title>, <locus>fol. 3 a</locus>; <quote xml:lang="syr">ܡܢ ܡܐܡܪܐ ܕܠܘܬ ܬܐܘܕܘܣܝܣ ܡ̇ܠܟܐ</quote>, <locus>fol. 2 b</locus>;...</p>
```

**Comment by davidamichelson** [comment]
Great work, this looks good. Please add to the manual!

**Comment by wlpotter** [comment]
Added to the manual
